### ISSUE TITLE
How to navigate with router-link on SPA mode ?

### ISSUE THREAD

**Issue by amrdevac** [akahon/vue-sidebar-menu-akahon#11]
How to navigate with router-link on SPA mode ? , right now every time we click it sidebar menu the navitated page is reloaded, so how to do it on SPA  where when we click on sidebar menu the page is navigate without need to reload

**Comment by akahon** [comment]
Updated v1.0.2
Added new props "isUsedVueRouter" boolean param by default "false". If you are using "vue-router", set the value to true.
Otherwise, when clicking on a menu item the <a> tag will be used by default and emitted the @menu-item-clicked event with the value of "item-link".

Example:
`
<VueSidebarMenuAkahon 
  :isUsedVueRouter="false" 
  @menu-item-clicked="fnRouteTo(link)"
/>
`
